### ISSUE TITLE
Not setting user claims in firebase

### ISSUE THREAD

**Issue by vlance11** [joserocha3/hasura-with-firebase#5]
When using the createUser function, we are successfully creating the user in Hasura and Firebase but when it comes to setting the claims it seems nothing is set in firebase.  

How would one double check this and verify?

**Comment by joserocha3** [comment]
Unfortunately, the Firebase console does not show custom claims. You will need to get the JWT and run it through something like [jwt.io](https://jwt.io/) or use Hasura's built in JWT parser in order to view the claims.

To get the JWT, in Chrome login as the created user, make an API then using chrome dev tools find the API request on the Network tab. The JWT is sent in the header of the request.

**Comment by joserocha3** [comment]
Please note that `createUser` is intended as an admin type function. The Firebase client library has its own call to sign up a new user and automatically log them in. In that case you could implement a Firebase function to add custom claims whenever a user is created.

**Comment by vlance11** [comment]
> Please note that `createUser` is intended as an admin type function. The Firebase client library has its own call to sign up a new user and automatically log them in. In that case you could implement a Firebase function to add custom claims whenever a user is created.

Sorry if I am a bit confused, I am referencing the Mutation.js file that looks as if it can set 3 roles ADMIN, CLIENT, MOBILE.  

These then could be called in the Frontend as the role upon logging into firebase?  It also sets the same role in the Hasura DB. 

Am I understanding this incorrectly?

**Comment by joserocha3** [comment]
Yes, you got it. The front end upon logging in can retrieve the custom claims using the firebase client sdk. And the custom claims will contain the role that is set upon creating the user.
